name: Learning CICD

on:
 push:
  branches: ["main"]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print the CICD
      run: echo "Hello, ther How are you"

    - name: check run or not
      run: |
        echo "running"
        ls -la
     

