name: Learning CICD

on:
 push:
  branches: ["main"]

# jobs:
#  build:
#   runs-on: ubuntu-latest

#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: setup java
#       uses: actions/setup-java@v4
#       with:
#          distribution: 'temurin'
#          java-version: '17'

#     - name: run maven
#       run: mvn clean package
#       working-directory: DemoAPP

#     - name: Copy to temp folder
#       run: |
#         mkdir temp
#         cp target/*.jar temp/

# - name: Copy JAR to temp
      #   run: |
      #     mkdir -p /tmp/myapp
      #     cp DemoAPP/target/*.jar /tmp/myapp/

      # - name: Verify JAR
      #   run: ls -l /tmp/myapp

# name: Deploying Java Application into git.

# on:
#  push:
#   branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Debug structure
        run: ls -R
        
      - name: Java Install
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'

      - name: Build Jar file
        run: mvn clean package -DskipTests
        working-directory: DemoAPP


      - name: Build Image into Docker
        working-directory: DemoAPP
        run: docker build -t demo-appv:${GITHUB_RUN_NUMBER} .

      - name: Check image file
        run: docker image

      