name: Learning CICD

on:
 push:
  branches: ["main"]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: setup java
      uses: actions/setup-java@v4
      with:
         distribution: 'temurin'
         java-version: '17'

    - name: run maven
      run: mvn clean package

